version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_audit
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: audit
      MYSQL_USER: audit
      MYSQL_PASSWORD: toor
    ports:
      - "3326:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - audit_network

volumes:
  mariadb_data:

networks:
  audit_network:
    driver: bridge
